name: clang-format

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Start container
      run: |
        docker run -it --name container \
                   --privileged \
                   -v ${GITHUB_WORKSPACE}:/Package \
                   -d ghcr.io/key4hep/key4hep-images/alma9-cvmfs:latest \
                   /bin/bash
    - name: Mount CVMFS
      run: |
        docker exec container /bin/bash -c '/mount.sh'
    - name: Add upstream
      run: |
        docker exec container /bin/bash -c 'cd Package; \
          git config --global --add safe.directory /Package; \
          git remote add upstream https://github.com/HEP-FCC/FCCAnalyses.git; \
          git fetch upstream'
    - name: Run formatter
      run: |
        docker exec container /bin/bash -c 'cd ./Package; \
          source /cvmfs/sw.hsf.org/key4hep/setup.sh;\
          git clang-format --diff --style=file $(git merge-base upstream/master HEAD)
          git clang-format --diffstat --style=file $(git merge-base upstream/master HEAD)'
